
public class JFrameGUI extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGUI
     */
    public JFrameGUI() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    public void serverDisplay() {
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new ServerGUI().setVisible(true);
                }
            });
        } catch (Exception ex) {
        }
    }

    public void clientDisplay() {
        try {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginGUI().setupLoginPanel();
                }
            });
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonServerGUI = new javax.swing.JButton();
        buttonUserGUI = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buttonServerGUI.setText("Server Page");
        buttonServerGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonServerGUIActionPerformed(evt);
            }
        });

        buttonUserGUI.setText("Login User Page");
        buttonUserGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUserGUIActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Communication System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonUserGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonServerGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(buttonServerGUI)
                .addGap(18, 18, 18)
                .addComponent(buttonUserGUI)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonServerGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonServerGUIActionPerformed
        // TODO add your handling code here:
        serverDisplay();
    }//GEN-LAST:event_buttonServerGUIActionPerformed

    private void buttonUserGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUserGUIActionPerformed
        // TODO add your handling code here:
        clientDisplay();
    }//GEN-LAST:event_buttonUserGUIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonServerGUI;
    private javax.swing.JButton buttonUserGUI;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
